### ISSUE TITLE
AttributeError in Application Example

### ISSUE THREAD

**Issue by danielgoncalves** [sebp/PyGObject-Tutorial#84] opened 2016-07-01 02:07 UTC
I am experiencing an `AttributeError` at [examples/application_example:97](https://github.com/sebp/PyGObject-Tutorial/blob/master/examples/application_example.py#L97)

```#!bash
$ python3 application_example.py 
Traceback (most recent call last):
  File "application_example.py", line 141, in <module>
    app = Application()
  File "application_example.py", line 97, in __init__
    self.add_main_option("test", ord("t"), GLib.OptionFlags.NONE,
AttributeError: 'Application' object has no attribute 'add_main_option'
```

* Python 3.4.3
* Gtk 3.10.8
* Ubuntu 14.04.4 LTS (64)

I tried to investigate the [`GtkApplication` API](https://developer.gnome.org/gtk3/stable/GtkApplication.html) documentation but I still have no idea where this method should be.

**Comment by TingPing** [comment] 2016-07-01 13:00
This was added with GLib 2.42 and before this there were no alternatives for Python bindings.

**Comment by sebp** [comment] 2016-09-26 19:58
Closing this, because it is not a bug.

**Closed by sebp** 2016-09-26 19:58 UTC
